format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$cmd_duration $time\
$line_break\
$character"""

[nodejs]
format = "[⬢ ($version )]($style)"

[fill]
symbol = " "

[username]
style_user = 'green bold'
style_root = 'red bold'
format = '[$user]($style)'
disabled = false
show_always = true


[hostname]
ssh_only = false
format = '[@](bold blue)[$hostname](bold green) '
trim_at = '.companyname.com'
disabled = false

[directory]
style = "cyan"
read_only = " 🔒"
truncation_length = 4
truncate_to_repo = false


[c]
format = 'via [$name $version]($style)'

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold purple"


[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold yellow"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[ $duration]($style)"
style = "bold yellow"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"